name: Deploy GitHub Pages

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run build
      - run: git config user.name "${GITHUB_ACTOR}" && git config user.email "test@example.com"
      - run: npm run deploy
